# Generated by Django 3.2.12 on 2022-11-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
